/* Configuration Module */
const CONFIG = {
  API: {
    BASE_URL: 'https://api.jsonbin.io/v3/b/686e6c4d5f4bcf6c3afb1182',
    API_KEY: '$2a$10$BqM/s2f2kqZGoB5V14WtWOPOVO5/ccx/wZtBqmQsgeQqh6WMp42We'
  },
  ASSET_TYPES: ['LAPTOP', 'DESKTOP', 'MONITOR', 'PRINTER', 'ROUTER', 'SWITCH', 'SCANNER', 'KEYBOARD', 'MOUSE', 'UPS', 'PROJECTOR', 'TABLET', 'PHONE', 'ACCESS POINT', 'SERVER', 'DOCKING STATION', 'WEBCAM', 'HEADSET', 'SPEAKER', 'EXTERNAL DRIVE', 'FLASH DRIVE', 'CABLES', 'ADAPTER', 'OTHER', 'TALLY'],
  AREA_OPTIONS: ['BULK', 'ONLINE', 'RETAIL', 'KIOSK RETAIL', 'KIOSK BULK', 'SILVERS', 'PRICING', 'RECEIVING', 'BARCODING', 'DAMAGES', 'OFFICE', 'CASH OFFICE', 'SPARE', 'TESTING', 'DUMPING', 'STORAGE'],
  APP_STATE: { ALL_ASSETS: [], CURRENT_TYPE: 'All Types', CURRENT_SEARCH: '', CURRENT_STATUS_FILTER: 'all' }
};